
-- Ajout des 175 activités partagées (accessibles à tous les profils)
-- ACTIVITÉS UNIVERSELLES - Partie 1 (75 activités)
INSERT INTO activities (title, description, type, activity_format, content, target_profiles, day_min, day_max, is_premium) VALUES
-- Activités de pleine conscience (15)
('Respiration consciente', 'Moment de présence par la respiration', 'morning', 'explanatory', '{"objective": "Développer la présence et le calme", "instructions": ["Asseyez-vous confortablement", "Fermez les yeux", "Concentrez-vous sur votre respiration naturelle", "Comptez 10 respirations", "Revenez au souffle quand l''esprit divague"], "duration": "5 minutes", "material": "Aucun", "why_helps": "La respiration consciente ancre dans le présent et calme le système nerveux."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 1, 365, false),
('Scan corporel', 'Exploration consciente des sensations', 'afternoon', 'explanatory', '{"objective": "Développer la conscience corporelle", "instructions": ["Allongez-vous confortablement", "Portez attention à vos pieds", "Remontez progressivement", "Observez chaque partie du corps", "Sans jugement, juste observer"], "duration": "15 minutes", "material": "Tapis ou lit", "why_helps": "Le scan corporel développe l''intéroception et réduit les tensions inconscientes."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 1, 365, false),
('Marche méditative', 'Méditation en mouvement', 'evening', 'explanatory', '{"objective": "Combiner mouvement et mindfulness", "instructions": ["Marchez très lentement", "Sentez chaque pas", "Coordonnez avec la respiration", "Restez présent au mouvement"], "duration": "10 minutes", "material": "Espace pour marcher", "why_helps": "La marche méditative unit corps et esprit dans la présence."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 1, 365, false),
('Observation des pensées', 'Regarder ses pensées sans s''y attacher', 'morning', 'explanatory', '{"objective": "Développer la distance avec les pensées", "instructions": ["Asseyez-vous tranquillement", "Observez vos pensées comme des nuages", "Ne les suivez pas, juste regardez", "Elles viennent et repartent naturellement"], "duration": "8 minutes", "material": "Aucun", "why_helps": "Observer les pensées crée une distance salutaire et réduit leur impact émotionnel."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 2, 365, false),
('Méditation des 5 sens', 'Présence par les sensations', 'afternoon', 'explanatory', '{"objective": "Ancrer dans le présent par les sens", "instructions": ["5 choses que vous voyez", "4 choses que vous entendez", "3 choses que vous touchez", "2 choses que vous sentez", "1 chose que vous goûtez"], "duration": "5 minutes", "material": "Aucun", "why_helps": "Cette technique ramène rapidement dans le moment présent via les sens."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 2, 365, false),
('Pause micro-méditation', 'Moments courts de présence', 'evening', 'explanatory', '{"objective": "Intégrer la mindfulness au quotidien", "instructions": ["3 respirations conscientes", "Plusieurs fois dans la journée", "Avant les repas, réunions, transitions", "Juste 30 secondes de présence"], "duration": "30 secondes x plusieurs", "material": "Aucun", "why_helps": "Les micro-méditations ancrent la pratique dans le quotidien."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 3, 365, false),
('Méditation du sourire', 'Bienveillance envers soi par le sourire', 'morning', 'explanatory', '{"objective": "Cultiver la bienveillance intérieure", "instructions": ["Souriez doucement", "Dirigez ce sourire vers votre cœur", "Ressentez la chaleur qui s''en dégage", "Maintenez cette bienveillance 5 minutes"], "duration": "5 minutes", "material": "Aucun", "why_helps": "Le sourire intérieur active les circuits neuronaux du bien-être."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 3, 365, false),
('Écoute consciente', 'Présence totale aux sons', 'afternoon', 'explanatory', '{"objective": "Développer l''attention auditive", "instructions": ["Fermez les yeux", "Écoutez tous les sons autour", "Proches et lointains", "Sans les nommer, juste entendre"], "duration": "7 minutes", "material": "Aucun", "why_helps": "L''écoute consciente développe la présence et calme le mental."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 4, 365, false),
('Méditation du thé', 'Rituel de présence par la boisson', 'evening', 'explanatory', '{"objective": "Transformer un geste quotidien en méditation", "instructions": ["Préparez votre boisson lentement", "Observez la vapeur, les couleurs", "Buvez la première gorgée en conscience", "Savourez chaque sensation"], "duration": "10 minutes", "material": "Thé ou boisson chaude", "why_helps": "Les rituels conscients transforment les gestes quotidiens en moments de paix."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 4, 365, false),
('Contemplation de la nature', 'Connexion consciente avec l''environnement', 'morning', 'explanatory', '{"objective": "Se connecter à la nature", "instructions": ["Trouvez un élément naturel", "Arbre, fleur, ciel, nuage", "Observez-le attentivement 10 minutes", "Ressentez votre connexion"], "duration": "10 minutes", "material": "Élément naturel", "why_helps": "La contemplation de la nature apaise et reconnecte à plus grand que soi."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 5, 365, false),
('Méditation des émotions', 'Accueil conscient des ressentis', 'afternoon', 'audio', '{"duration": 480, "theme": "emotions-awareness-meditation", "objective": "Développer l''intelligence émotionnelle", "instructions": ["Observez vos émotions sans jugement", "Accueillez-les comme des invitées", "Elles ont toutes leur message"], "why_helps": "Cette méditation développe une relation saine avec toutes les émotions."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 5, 365, false),
('Pause gratitude', 'Moment de reconnaissance consciente', 'evening', 'explanatory', '{"objective": "Cultiver la gratitude au quotidien", "instructions": ["Trois fois par jour", "Identifiez une chose pour laquelle vous êtes reconnaissant", "Ressentez vraiment cette gratitude", "Laissez-la vous remplir"], "duration": "2 minutes x 3", "material": "Aucun", "why_helps": "La gratitude régulière rewire le cerveau vers le positif."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 6, 365, false),
('Méditation du cœur', 'Connexion à la sagesse du cœur', 'morning', 'audio', '{"duration": 540, "theme": "heart-wisdom-meditation", "objective": "Développer l''intelligence du cœur", "instructions": ["Placez votre main sur votre cœur", "Respirez dans cette zone", "Écoutez sa sagesse"], "why_helps": "Le cœur possède sa propre intelligence, complémentaire au mental."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 6, 365, false),
('Observation du ciel', 'Méditation par la contemplation céleste', 'afternoon', 'explanatory', '{"objective": "S''ouvrir à l''immensité", "instructions": ["Regardez le ciel 10 minutes", "Jour ou nuit, peu importe", "Ressentez votre place dans l''univers", "Laissez l''immensité vous apaiser"], "duration": "10 minutes", "material": "Vue sur le ciel", "why_helps": "La contemplation du ciel relativise les problèmes et ouvre la perspective."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 7, 365, false),
('Méditation de l''instant présent', 'Pure présence sans objet', 'evening', 'audio', '{"duration": 600, "theme": "pure-presence-meditation", "objective": "Cultiver la présence pure", "instructions": ["Juste être présent", "Sans se concentrer sur rien de particulier", "Juste être"], "why_helps": "La présence pure est l''état naturel de paix de l''esprit."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 7, 365, false),

-- Activités de gestion du stress (15)
('Respiration 4-4-4', 'Technique de respiration équilibrée', 'morning', 'explanatory', '{"objective": "Réguler le système nerveux", "instructions": ["Inspirez sur 4 temps", "Retenez sur 4 temps", "Expirez sur 4 temps", "Répétez 10 cycles"], "duration": "5 minutes", "material": "Aucun", "why_helps": "Cette respiration équilibre le système nerveux autonome."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 1, 365, false),
('Relaxation progressive', 'Détente systématique du corps', 'afternoon', 'audio', '{"duration": 900, "theme": "progressive-relaxation", "objective": "Relâcher toutes les tensions", "instructions": ["Contractez puis relâchez chaque groupe musculaire", "Commencez par les pieds", "Remontez jusqu''à la tête"], "why_helps": "La relaxation progressive libère les tensions physiques et mentales."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 1, 365, false),
('Technique STOP', 'Interruption des spirales de stress', 'evening', 'explanatory', '{"objective": "Interrompre les spirales négatives", "instructions": ["S : Stop - Arrêtez-vous", "T : Take a breath - Respirez", "O : Observe - Observez la situation", "P : Perspective - Prenez du recul"], "duration": "2 minutes", "material": "Aucun", "why_helps": "Cette technique interrompt les automatismes de stress."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 2, 365, false),
('Visualisation d''un lieu sûr', 'Refuge mental apaisant', 'morning', 'audio', '{"duration": 480, "theme": "safe-place-visualization", "objective": "Créer un refuge intérieur", "instructions": ["Visualisez votre lieu parfait de sécurité", "Engagez tous vos sens", "Ancrez cette sensation"], "why_helps": "Un lieu sûr intérieur est accessible en permanence pour l''apaisement."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 2, 365, false),
('Auto-massage anti-stress', 'Détente par le toucher thérapeutique', 'afternoon', 'explanatory', '{"objective": "Relâcher les tensions par le toucher", "instructions": ["Massez vos tempes en cercles", "Pétrissez vos épaules", "Massez vos mains et poignets", "Respirez profondément"], "duration": "8 minutes", "material": "Aucun", "why_helps": "L''auto-massage libère les tensions et apaise le système nerveux."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 3, 365, false),
('Journal de décompression', 'Évacuation des tensions par l''écriture', 'evening', 'notebook', '{"objective": "Libérer le stress accumulé", "prompt": "Videz votre esprit sur papier. Écrivez tout ce qui vous préoccupe, sans ordre ni logique. Puis froissez la feuille et jetez-la.", "duration": "10 minutes", "material": "Papier, stylo", "why_helps": "L''écriture libératrice évacue le stress mental accumulé."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 3, 365, false),
('Méditation de la montagne', 'Stabilité et sérénité intérieures', 'morning', 'audio', '{"duration": 600, "theme": "mountain-stability-meditation", "objective": "Développer la stabilité intérieure", "instructions": ["Visualisez-vous comme une montagne", "Stable, inébranlable", "Les nuages-pensées passent"], "why_helps": "Cette méditation développe un centre de calme inébranlable."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 4, 365, false),
('Étirements de décompression', 'Relâchement des tensions corporelles', 'afternoon', 'explanatory', '{"objective": "Libérer les tensions physiques", "instructions": ["Étirez le cou doucement", "Roulez les épaules", "Étirez le dos", "Respirez dans chaque étirement"], "duration": "10 minutes", "material": "Aucun", "why_helps": "Les étirements libèrent les tensions physiques liées au stress."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 4, 365, false),
('Technique de la cohérence cardiaque', 'Synchronisation cœur-cerveau', 'evening', 'explanatory', '{"objective": "Optimiser la variabilité cardiaque", "instructions": ["Respirez 5 secondes à l''inspiration", "5 secondes à l''expiration", "Maintenez ce rythme 5 minutes", "Concentrez-vous sur votre cœur"], "duration": "5 minutes", "material": "Aucun", "why_helps": "La cohérence cardiaque optimise l''équilibre du système nerveux autonome."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 5, 365, false),
('Bain sonore', 'Détente par les vibrations sonores', 'morning', 'audio', '{"duration": 720, "theme": "sound-bath-relaxation", "objective": "Relaxation profonde par le son", "instructions": ["Allongez-vous confortablement", "Laissez les sons vous traverser", "Abandonnez-vous aux vibrations"], "why_helps": "Les vibrations sonores induisent un état de relaxation profonde."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 5, 365, false),
('Technique de l''ancrage', 'Stabilisation dans le moment présent', 'afternoon', 'explanatory', '{"objective": "Se stabiliser dans le présent", "instructions": ["Sentez vos pieds au sol", "Nommez 3 objets que vous voyez", "2 sons que vous entendez", "1 sensation physique"], "duration": "3 minutes", "material": "Aucun", "why_helps": "L''ancrage ramène rapidement dans le présent et stabilise."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 6, 365, false),
('Méditation de la rivière', 'Fluidité et lâcher-prise', 'evening', 'audio', '{"duration": 540, "theme": "flowing-river-meditation", "objective": "Cultiver le flow et le lâcher-prise", "instructions": ["Visualisez une rivière paisible", "Vos stress sont des feuilles sur l''eau", "Elles s''éloignent naturellement"], "why_helps": "Cette méditation cultive le lâcher-prise et la fluidité."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 6, 365, false),
('Respiration abdominale', 'Activation du système de récupération', 'morning', 'explanatory', '{"objective": "Activer la relaxation naturelle", "instructions": ["Main sur le ventre", "Respirez lentement par le nez", "Le ventre se gonfle à l''inspiration", "Se dégonfle à l''expiration"], "duration": "8 minutes", "material": "Aucun", "why_helps": "La respiration abdominale active le nerf vague et la relaxation."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 7, 365, false),
('Micro-sieste récupératrice', 'Repos réparateur de courte durée', 'afternoon', 'explanatory', '{"objective": "Récupérer rapidement de l''énergie", "instructions": ["Allongez-vous 10-20 minutes", "Fermez les yeux", "Respirez calmement", "Même sans dormir, reposez-vous"], "duration": "10-20 minutes", "material": "Endroit calme", "why_helps": "Les micro-siestes restaurent l''énergie et réduisent le stress."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 7, 365, false),
('Rituel de fin de journée', 'Transition vers la détente', 'evening', 'explanatory', '{"objective": "Marquer la fin du stress quotidien", "instructions": ["Prenez une douche consciente", "Changez de vêtements", "Allumez une bougie", "Déclarez la journée terminée"], "duration": "15 minutes", "material": "Éléments de rituel", "why_helps": "Les rituels marquent symboliquement la transition et aident à lâcher prise."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 8, 365, false),

-- Activités d''auto-compassion (15)
('Méditation de bienveillance', 'Cultiver la bonté envers soi', 'morning', 'audio', '{"duration": 540, "theme": "self-compassion-meditation", "objective": "Développer l''auto-compassion", "instructions": ["Dirigez de la bienveillance vers vous-même", "Comme vers un ami cher", "Vous méritez la même bonté"], "why_helps": "L''auto-compassion réduit l''auto-critique et améliore le bien-être."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 1, 365, false),
('Lettre à soi-même', 'Dialogue bienveillant avec soi', 'afternoon', 'notebook', '{"objective": "Pratiquer l''auto-compassion écrite", "prompt": "Écrivez-vous une lettre comme à votre meilleur ami. Que lui diriez-vous pour le réconforter ? Dites-vous les mêmes choses.", "duration": "15 minutes", "material": "Carnet", "why_helps": "S''écrire avec bienveillance développe une relation positive avec soi."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 1, 365, false),
('Mantra de compassion', 'Phrases apaisantes pour soi', 'evening', 'explanatory', '{"objective": "Installer des messages bienveillants", "instructions": ["Répétez : ''Je suis humain et imparfait''", "''Je mérite compassion et bonté''", "''Je fais de mon mieux avec ce que j''ai''", "Laissez ces mots vous pénétrer"], "duration": "5 minutes", "material": "Aucun", "why_helps": "Les mantras compassionnels reprogramment le dialogue intérieur."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 2, 365, false),
('Caresse apaisante', 'Auto-réconfort par le toucher', 'morning', 'explanatory', '{"objective": "S''apaiser par le contact physique", "instructions": ["Placez la main sur votre cœur", "Caressez doucement votre bras", "Ou massez vos mains", "Avec la tendresse d''une mère"], "duration": "5 minutes", "material": "Aucun", "why_helps": "Le toucher bienveillant libère de l''ocytocine et apaise."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 2, 365, false),
('Journal des qualités', 'Reconnaissance de ses forces', 'afternoon', 'notebook', '{"objective": "Équilibrer l''auto-critique", "prompt": "Listez 10 de vos qualités, même petites. Pour chacune, donnez un exemple concret récent. Célébrez ces aspects positifs de vous.", "duration": "12 minutes", "material": "Carnet", "why_helps": "Reconnaître ses qualités équilibre l''auto-critique excessive."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 3, 365, false),
('Méditation du pardon de soi', 'Libération de la culpabilité', 'evening', 'audio', '{"duration": 600, "theme": "self-forgiveness-meditation", "objective": "Se libérer de la culpabilité", "instructions": ["Pensez à quelque chose que vous vous reprochez", "Offrez-vous le pardon", "Vous êtes humain et apprenez"], "why_helps": "Le pardon de soi libère de la culpabilité toxique et permet d''avancer."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 3, 365, false),
('Dialogue intérieur bienveillant', 'Changer le ton de sa voix intérieure', 'morning', 'explanatory', '{"objective": "Transformer l''auto-critique", "instructions": ["Observez votre dialogue intérieur", "Quand il devient critique, stop", "Reformulez avec bienveillance", "Comme parleriez-vous à un ami ?"], "duration": "Variable", "material": "Aucun", "why_helps": "Changer le dialogue intérieur transforme la relation avec soi."}', ARRAY['anxieux', 'fatigue', 'deracine', 'controlant', 'hypersensible', 'refoule', 'volcan'], 4, 365, false);
