
-- Migration corrigée avec la bonne syntaxe PostgreSQL pour les arrays
-- 25 activités exclusives pour L'ANXIEUX

-- Supprimer les activités existantes pour éviter les doublons
DELETE FROM activities;

-- ACTIVITÉS EXCLUSIVES POUR L'ANXIEUX (25)
INSERT INTO activities (title, description, type, activity_format, content, target_profiles, day_min, day_max, is_premium) VALUES
('Respiration 4-7-8', 'Technique de respiration pour calmer l''anxiété instantanément', 'morning', 'explanatory', '{"objective": "Réduire l''anxiété par la respiration", "instructions": ["Inspirez par le nez en comptant jusqu''à 4", "Retenez votre souffle en comptant jusqu''à 7", "Expirez par la bouche en comptant jusqu''à 8", "Répétez 4 cycles"], "duration": "5 minutes", "material": "Aucun", "why_helps": "Cette technique active le système nerveux parasympathique, réduisant immédiatement les symptômes d''anxiété."}', ARRAY['anxieux'], 1, 365, false),
('Scan corporel anti-stress', 'Détection et relâchement des tensions physiques', 'afternoon', 'explanatory', '{"objective": "Identifier et relâcher les tensions", "instructions": ["Allongez-vous confortablement", "Scannez votre corps de la tête aux pieds", "Identifiez les zones tendues", "Contractez puis relâchez chaque zone", "Respirez profondément"], "duration": "15 minutes", "material": "Tapis ou lit", "why_helps": "La tension physique amplifie l''anxiété. Ce scan permet de briser ce cercle vicieux."}', ARRAY['anxieux'], 1, 365, false),
('Journal des inquiétudes', 'Technique pour externaliser et rationaliser les peurs', 'evening', 'notebook', '{"objective": "Réduire les ruminations anxieuses", "prompt": "Listez 3 inquiétudes actuelles. Pour chacune, écrivez : Est-ce réel ou imaginaire ? Puis-je agir dessus ? Si oui, comment ? Si non, comment lâcher prise ?", "duration": "10 minutes", "material": "Carnet et stylo", "why_helps": "Écrire les inquiétudes les extériorise et permet une analyse rationnelle plutôt qu''émotionnelle."}', ARRAY['anxieux'], 2, 365, false),
('Méditation de sécurité', 'Visualisation d''un lieu sûr pour l''apaisement', 'morning', 'audio', '{"duration": 600, "theme": "safe-place-meditation", "objective": "Créer un ancrage de sécurité intérieure", "instructions": ["Trouvez un endroit calme", "Fermez les yeux", "Visualisez votre lieu de sécurité parfait", "Ancrez cette sensation"], "why_helps": "La visualisation d''un lieu sûr active les zones cérébrales liées au calme et à la sécurité."}', ARRAY['anxieux'], 3, 365, false),
('Technique de grounding 5-4-3-2-1', 'Ancrage sensoriel contre les crises d''anxiété', 'afternoon', 'explanatory', '{"objective": "Revenir au moment présent", "instructions": ["Nommez 5 choses que vous voyez", "4 choses que vous touchez", "3 choses que vous entendez", "2 choses que vous sentez", "1 chose que vous goûtez"], "duration": "5 minutes", "material": "Aucun", "why_helps": "Cette technique ramène l''attention sur le présent, interrompant le cycle des pensées anxieuses."}', ARRAY['anxieux'], 4, 365, false),
('Affirmations personnalisées', 'Phrases positives contre les pensées négatives', 'morning', 'explanatory', '{"objective": "Remplacer les pensées négatives", "instructions": ["Identifiez votre peur principale", "Créez une affirmation positive opposée", "Répétez 10 fois devant un miroir", "Répétez mentalement dans la journée"], "duration": "10 minutes", "material": "Miroir", "why_helps": "Les affirmations reprogramment progressivement les schémas de pensée négatifs."}', ARRAY['anxieux'], 5, 365, false),
('Relaxation musculaire progressive', 'Détente profonde par la contraction-relâchement', 'evening', 'audio', '{"duration": 900, "theme": "progressive-muscle-relaxation", "objective": "Détente physique complète", "instructions": ["Allongez-vous confortablement", "Suivez le guide audio", "Contractez et relâchez chaque groupe musculaire"], "why_helps": "La relaxation musculaire réduit la tension physique qui maintient l''anxiété."}', ARRAY['anxieux'], 6, 365, false),
('Plan d''urgence anxiété', 'Stratégie personnelle pour les crises', 'afternoon', 'notebook', '{"objective": "Préparer les moments difficiles", "prompt": "Créez votre kit de survie anxiété : 5 techniques rapides qui marchent pour vous, 3 personnes à contacter, 2 lieux où vous sentir mieux, 1 phrase qui vous rassure.", "duration": "15 minutes", "material": "Carnet", "why_helps": "Avoir un plan préparé réduit l''anxiété liée à l''imprévisibilité des crises."}', ARRAY['anxieux'], 7, 365, false),
('Méditation de compassion', 'Bienveillance envers soi-même', 'morning', 'audio', '{"duration": 480, "theme": "self-compassion", "objective": "Développer l''auto-compassion", "instructions": ["Placez vos mains sur votre cœur", "Suivez la méditation guidée", "Envoyez-vous de la bienveillance"], "why_helps": "L''auto-compassion réduit l''anxiété en diminuant l''auto-critique."}', ARRAY['anxieux'], 8, 365, false),
('Exercice de perspective', 'Relativiser les problèmes par le recul', 'evening', 'explanatory', '{"objective": "Prendre du recul sur les problèmes", "instructions": ["Pensez à votre inquiétude actuelle", "Imaginez-vous dans 1 an : sera-ce encore important ?", "Et dans 10 ans ?", "Notez ce que cela change"], "duration": "10 minutes", "material": "Aucun", "why_helps": "La perspective temporelle aide à relativiser et réduire l''intensité émotionnelle."}', ARRAY['anxieux'], 9, 365, false),
('Cohérence cardiaque', 'Synchronisation cœur-cerveau pour l''apaisement', 'afternoon', 'explanatory', '{"objective": "Réguler le système nerveux", "instructions": ["Inspirez 5 secondes", "Expirez 5 secondes", "Maintenez ce rythme 5 minutes", "Concentrez-vous sur votre cœur"], "duration": "5 minutes", "material": "Aucun", "why_helps": "La cohérence cardiaque optimise la variabilité cardiaque, réduisant stress et anxiété."}', ARRAY['anxieux'], 10, 365, false),
('Visualisation positive', 'Imaginer des scénarios apaisants', 'morning', 'audio', '{"duration": 720, "theme": "positive-visualization", "objective": "Programmer l''esprit positivement", "instructions": ["Installez-vous confortablement", "Visualisez votre journée idéale", "Ressentez les émotions positives"], "why_helps": "La visualisation positive prépare l''esprit à vivre des expériences apaisantes."}', ARRAY['anxieux'], 11, 365, false),
('Technique STOP', 'Interruption des spirales anxieuses', 'afternoon', 'explanatory', '{"objective": "Arrêter les pensées négatives", "instructions": ["S : Stop - Arrêtez-vous", "T : Take a breath - Respirez", "O : Observe - Observez vos sensations", "P : Proceed - Continuez avec conscience"], "duration": "2 minutes", "material": "Aucun", "why_helps": "Cette technique interrompt les spirales de pensées anxieuses avant qu''elles s''amplifient."}', ARRAY['anxieux'], 12, 365, false),
('Journal de gratitude anti-anxiété', 'Focus sur le positif pour réduire l''anxiété', 'evening', 'notebook', '{"objective": "Réorienter vers le positif", "prompt": "Notez 3 choses pour lesquelles vous êtes reconnaissant aujourd''hui. Pour chacune, décrivez pourquoi elle vous apaise ou vous rassure.", "duration": "10 minutes", "material": "Carnet", "why_helps": "La gratitude active les circuits neuronaux du bien-être, réduisant l''anxiété."}', ARRAY['anxieux'], 13, 365, false),
('Auto-massage apaisant', 'Techniques de massage pour se calmer', 'morning', 'explanatory', '{"objective": "Détente par le toucher", "instructions": ["Massez vos tempes en cercles", "Pétrissez vos épaules", "Caressez vos bras", "Pressez le point entre pouce et index"], "duration": "8 minutes", "material": "Aucun", "why_helps": "Le toucher libère de l''ocytocine, hormone de l''apaisement et du lien social."}', ARRAY['anxieux'], 14, 365, false),
('Défis graduels', 'Exposition progressive aux peurs', 'afternoon', 'notebook', '{"objective": "Réduire l''évitement", "prompt": "Choisissez une peur mineure. Créez 5 étapes pour l''affronter progressivement. Commencez par l''étape 1 cette semaine.", "duration": "15 minutes", "material": "Carnet", "why_helps": "L''exposition graduelle réduit l''anxiété en prouvant que les peurs sont souvent irrationnelles."}', ARRAY['anxieux'], 15, 365, false),
('Méditation des sons', 'Apaisement par les sons naturels', 'evening', 'audio', '{"duration": 600, "theme": "nature-sounds-meditation", "objective": "Calmer par les sons", "instructions": ["Écoutez les sons naturels", "Laissez-vous porter", "Respirez au rythme des sons"], "why_helps": "Les sons naturels activent la réponse de relaxation du système nerveux."}', ARRAY['anxieux'], 16, 365, false),
('Ancrage par les objets', 'Utiliser des objets réconfortants', 'morning', 'explanatory', '{"objective": "Créer des points d''ancrage", "instructions": ["Choisissez un objet réconfortant", "Tenez-le lors de moments anxieux", "Associez-le à un souvenir apaisant", "Utilisez-le comme ancre de sécurité"], "duration": "Variable", "material": "Objet personnel", "why_helps": "Les objets transitionnels fournissent une sécurité émotionnelle tangible."}', ARRAY['anxieux'], 17, 365, false),
('Restructuration cognitive', 'Changer les pensées négatives', 'afternoon', 'notebook', '{"objective": "Modifier les schémas de pensée", "prompt": "Identifiez une pensée anxieuse récurrente. Questionnez-la : Est-ce factuel ? Y a-t-il d''autres explications possibles ? Reformulez-la de façon plus équilibrée.", "duration": "12 minutes", "material": "Carnet", "why_helps": "La restructuration cognitive change les patterns de pensée qui alimentent l''anxiété."}', ARRAY['anxieux'], 18, 365, false),
('Hygiène du sommeil anti-anxiété', 'Préparer un sommeil réparateur', 'evening', 'explanatory', '{"objective": "Améliorer la qualité du sommeil", "instructions": ["Éteignez les écrans 1h avant", "Préparez une tisane calmante", "Lisez quelques pages", "Pratiquez une respiration lente"], "duration": "30 minutes", "material": "Livre, tisane", "why_helps": "Un bon sommeil régule les hormones de stress et réduit l''anxiété du lendemain."}', ARRAY['anxieux'], 19, 365, false),
('Technique de l''arbre', 'Ancrage et stabilité par la visualisation', 'morning', 'explanatory', '{"objective": "Développer la stabilité intérieure", "instructions": ["Debout, imaginez être un arbre", "Vos pieds sont des racines profondes", "Votre tronc est solide et flexible", "Vos branches dansent avec le vent"], "duration": "8 minutes", "material": "Aucun", "why_helps": "Cette visualisation développe un sentiment de stabilité et d''enracinement."}', ARRAY['anxieux'], 20, 365, false),
('Communication assertive', 'Exprimer ses besoins sans anxiété', 'afternoon', 'explanatory', '{"objective": "Réduire l''anxiété sociale", "instructions": ["Identifiez un besoin non exprimé", "Formulez-le avec ''Je''", "Exprimez-le clairement et calmement", "Acceptez la réponse sans vous justifier"], "duration": "Variable", "material": "Aucun", "why_helps": "L''assertivité réduit l''anxiété liée à la peur du conflit et du rejet."}', ARRAY['anxieux'], 21, 365, false),
('Méditation de la montagne', 'Stabilité et sérénité par la visualisation', 'evening', 'audio', '{"duration": 840, "theme": "mountain-meditation", "objective": "Développer la stabilité intérieure", "instructions": ["Visualisez-vous comme une montagne", "Solide, inébranlable", "Les nuages (pensées) passent"], "why_helps": "Cette méditation développe un sentiment de stabilité face aux turbulences émotionnelles."}', ARRAY['anxieux'], 22, 365, false),
('Planification anti-procrastination', 'Réduire l''anxiété par l''organisation', 'morning', 'notebook', '{"objective": "Réduire l''anxiété de performance", "prompt": "Choisissez une tâche qui vous angoisse. Décomposez-la en 5 petites étapes. Planifiez quand faire chaque étape cette semaine.", "duration": "15 minutes", "material": "Carnet, agenda", "why_helps": "La planification réduit l''anxiété en donnant un sentiment de contrôle et de faisabilité."}', ARRAY['anxieux'], 23, 365, false),
('Respiration alternée', 'Équilibrer le système nerveux', 'afternoon', 'explanatory', '{"objective": "Équilibrer les hémisphères cérébraux", "instructions": ["Bouchez la narine droite, inspirez à gauche", "Bouchez la narine gauche, expirez à droite", "Inspirez à droite", "Expirez à gauche", "Répétez 10 cycles"], "duration": "10 minutes", "material": "Aucun", "why_helps": "Cette respiration équilibre le système nerveux autonome et calme l''esprit."}', ARRAY['anxieux'], 24, 365, false),
('Rituel de protection', 'Créer un sentiment de sécurité quotidien', 'evening', 'explanatory', '{"objective": "Installer une routine sécurisante", "instructions": ["Créez un petit rituel personnel", "Allumez une bougie ou diffusez une huile", "Récitez une phrase positive", "Visualisez une bulle de protection"], "duration": "10 minutes", "material": "Bougie ou huiles", "why_helps": "Les rituels créent un sentiment de contrôle et de sécurité, réduisant l''anxiété."}', ARRAY['anxieux'], 25, 365, false);
