// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvxsywwscdcxrpshmrrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12eHN5d3dzY2RjeHJwc2htcnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTA5MTksImV4cCI6MjA2NTg2NjkxOX0.Hj8sS7aAxzsemoZjuU1HinismI17SC2klWFizlvzndI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);